# Generated by Django 2.2.5 on 2019-09-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('post_id', models.CharField(max_length=20, verbose_name='Reddit post ID')),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.URLField()),
                ('url', models.URLField()),
            ],
        ),
    ]
